version: '2'

services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 81:80
    volumes:
      - ./mount/php.conf:/etc/nginx/conf.d/default.conf
      - ./data:/usr/share/nginx/html
    depends_on:
      - php
  php:
    container_name: php
    image: php:7-fpm-alpine
    volumes:
      - ./data:/usr/share/nginx/html